[images]
  remote_images = [
    "https://source.unsplash.com/.*",
    "https://images.unsplash.com/.*",
    "https://ext.same-assets.com/.*",
    "https://ugc.same-assets.com/.*"
  ]

[build]
  command = "bun run build:deploy"
  # Let the plugin control the publish directory (it will set to `.netlify/output`)
  # publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  SKIP_TYPE_CHECK = "true"
  SKIP_LINT = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  NEXT_DISABLE_TYPESCRIPT = "true"
  NEXT_DISABLE_ESLINT = "true"
  # DO NOT SKIP the plugin if you want SSR:
  # NETLIFY_NEXT_PLUGIN_SKIP = "true"   <--- REMOVE this line!

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# API Routes Configuration
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# DO NOT use this SPA fallback if you want SSR!
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
#   conditions = { Role = ["client"] }

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https: wss: ws:; font-src 'self' data:;"

# Cache optimization
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify dashboard, NOT here)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# OPENAI_API_KEY
# ANTHROPIC_API_KEY
# DEEPSEEK_API_KEY
